# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  create-cluster:
      cmds:
        - kind create cluster --config kind-config.yml
      desc: Creates a kubernetes cluster using kind

  delete-cluster:
    cmds:
      - kind delete cluster
    desc: Deletes the cluster

  install-metallb:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
    desc: Installs MetalLB by manifest into the cluster